app:
  name: GinChat
  port: 8082
  env: dev
mysql:
  dns: root:1234@tcp(172.18.91.89:3306)/ginchat?charset=utf8mb4&parseTime=True&loc=Local
#redis:
#  addr: "172.18.91.89:6379"
#  password: ""
#  DB: 0
#  poolSize: 30
#  minIdleConn: 30

redis:
  cluster:
    # 虚拟机 Docker 中 Redis 集群的节点列表（需填写实际虚拟机IP+集群端口）
    addrs:
      - "172.18.91.89:7000"
      - "172.18.91.89:7001"
      - "172.18.91.89:7002"
      - "172.18.91.89:7003"
      - "172.18.91.89:7004"
      - "172.18.91.89:7005"
    password: ""
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s

oss:
  Endpoint: "oss-cn-hangzhou.aliyuncs.com"
  AccessKeyId: "LTAI5tNCXPJwS3MstKoKgixh"
  AccessKeySecret: "YhHE8OyCMsqfjwOnxQ1oO7paYlDjVHX"
  Bucket : "ginchat"

timeout:
  DelayHeartbeat: 3   #延迟心跳时间  单位秒
  HeartbeatHz: 30   #每隔多少秒心跳时间   
  HeartbeatMaxTime: 30000  #最大心跳时间  ，超过此就下线 
  RedisOnlineTime: 4  #缓存的在线用户时长   单位H

port:
  server: ":8082"
  udp: 3001
